# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
VAGRANTFILE_API_VERSION = '2'

config_file=File.expand_path(File.join(File.dirname(__FILE__), 'vagrant_variables.yml'))

settings=YAML.load_file(config_file)

LABEL_PREFIX    = settings['label_prefix'] ? settings['label_prefix'] + "-" : ""
CONTROLS        = settings['control_vms']
SEEDS           = settings['seed_vms']
BAREMETALS      = settings['baremetal_vms']
PUBLIC_SUBNET   = settings['public_subnet']
CLUSTER_SUBNET  = settings['cluster_subnet']
BOX             = ENV['CEPH_ANSIBLE_VAGRANT_BOX'] || settings['vagrant_box']
#CLIENT_BOX      = ENV['CEPH_ANSIBLE_VAGRANT_BOX'] || settings['client_vagrant_box'] || BOX
BOX_URL         = ENV['CEPH_ANSIBLE_VAGRANT_BOX_URL'] || settings['vagrant_box_url']
SYNC_DIR        = settings['vagrant_sync_dir']
MEMORY          = settings['memory']
ETH             = settings['eth']
#DOCKER          = settings['docker']
USER            = settings['ssh_username']
DEBUG           = settings['debug']

ASSIGN_STATIC_IP = !(BOX == 'openstack' or BOX == 'linode')
DISABLE_SYNCED_FOLDER = settings.fetch('vagrant_disable_synced_folder', false)

$last_ip_pub_digit   = 9
$last_ip_cluster_digit = 9

ansible_provision = proc do |ansible|
  if DOCKER then
    ansible.playbook = 'site-container.yml'
    if settings['skip_tags']
      ansible.skip_tags = settings['skip_tags']
    end
  else
    ansible.playbook = 'site.yml'
  end

  # Note: Can't do ranges like mon[0-2] in groups because
  # these aren't supported by Vagrant, see
  # https://github.com/mitchellh/vagrant/issues/3539
  ansible.groups = {
    'controls'         => (0..CONTROLS - 1).map { |j| "#{LABEL_PREFIX}control#{j}" },
    'seeds'            => (0..SEEDS - 1).map { |j| "#{LABEL_PREFIX}seed#{j}" },
    'baremetals'       => (0..BAREMETALS - 1).map { |j| "#{LABEL_PREFIX}baremetal#{j}" }
  }

  ansible.extra_vars = {
      cluster_network: "#{CLUSTER_SUBNET}.0/24",
      journal_size: 100,
      public_network: "#{PUBLIC_SUBNET}.0/24",
  }

#  # In a production deployment, these should be secret
#  if DOCKER then
#    ansible.extra_vars = ansible.extra_vars.merge({
#      containerized_deployment: 'true',
#      monitor_interface: ETH,
#      ceph_mon_docker_subnet: "#{PUBLIC_SUBNET}.0/24",
#      devices: settings['disks'],
#      radosgw_interface: ETH,
#      generate_fsid: 'true',
#    })
#  else
    ansible.extra_vars = ansible.extra_vars.merge({
      devices: settings['disks'],
      monitor_interface: ETH,
      radosgw_interface: ETH,
      os_tuning_params: settings['os_tuning_params'],
    })
#  end

  if BOX == 'linode' then
    ansible.sudo = true
    # Use monitor_address_block instead of monitor_interface:
    ansible.extra_vars.delete(:monitor_interface)
    # Use radosgw_address_block instead of radosgw_interface:
    ansible.extra_vars.delete(:radosgw_interface)
    ansible.extra_vars = ansible.extra_vars.merge({
      cluster_network: "#{CLUSTER_SUBNET}.0/16",
      devices: ['/dev/sdc'], # hardcode leftover disk
      monitor_address_block: "#{PUBLIC_SUBNET}.0/16",
      radosgw_address_block: "#{PUBLIC_SUBNET}.0/16",
      public_network: "#{PUBLIC_SUBNET}.0/16",
    })
  end

  if DEBUG then
    ansible.verbose = '-vvvv'
  end
  ansible.limit = 'all'
end

def create_vmdk(name, size)
  dir = Pathname.new(__FILE__).expand_path.dirname
  path = File.join(dir, '.vagrant', name + '.vmdk')
  `vmware-vdiskmanager -c -s #{size} -t 0 -a scsi #{path} \
   2>&1 > /dev/null` unless File.exist?(path)
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX
  config.vm.box_url = BOX_URL
  config.ssh.insert_key = false # workaround for https://github.com/mitchellh/vagrant/issues/5048
  config.ssh.private_key_path = settings['ssh_private_key_path']
  config.ssh.username = USER

  # When using libvirt, avoid errors like:
  # "host doesn't support requested feature: CPUID.01H:EDX.ds [bit 21]"
  config.vm.provider :libvirt do |lv|
    lv.cpu_mode = 'host-passthrough'
    lv.volume_cache = 'unsafe'
    lv.graphics_type = 'none'
    lv.cpus = 4
  end

  # Faster bootup. Disables mounting the sync folder for libvirt and virtualbox
  if DISABLE_SYNCED_FOLDER
    config.vm.provider :virtualbox do |v,override|
      override.vm.synced_folder '.', SYNC_DIR, disabled: true
    end
    config.vm.provider :libvirt do |v,override|
      override.vm.synced_folder '.', SYNC_DIR, disabled: true
    end
  end

  if BOX == 'openstack'
    # OpenStack VMs
    config.vm.provider :openstack do |os|
      config.vm.synced_folder ".", "/home/#{USER}/vagrant", disabled: true
      config.ssh.pty = true
      os.openstack_auth_url = settings['os_openstack_auth_url']
      os.username = settings['os_username']
      os.password = settings['os_password']
      os.tenant_name = settings['os_tenant_name']
      os.region = settings['os_region']
      os.flavor = settings['os_flavor']
      os.image = settings['os_image']
      os.keypair_name = settings['os_keypair_name']
      os.security_groups = ['default']

      if settings['os_networks'] then
        os.networks = settings['os_networks']
      end

      if settings['os_floating_ip_pool'] then
        os.floating_ip_pool = settings['os_floating_ip_pool']
      end

      config.vm.provision "shell", inline: "true", upload_path: "/home/#{USER}/vagrant-shell"
    end
  elsif BOX == 'linode'
    config.vm.provider :linode do |provider, override|
      provider.token = ENV['LINODE_API_KEY']
      provider.distribution = settings['cloud_distribution'] # 'Ubuntu 16.04 LTS'
      provider.datacenter = settings['cloud_datacenter']
      provider.plan = MEMORY.to_s
      provider.private_networking = true
      # root install generally takes <1GB
      provider.xvda_size = 4*1024
      # add some swap as the Linode distros require it
      provider.swap_size = 128
    end
  end


  (0..CONTROLS - 1).each do |i|
    config.vm.define "#{LABEL_PREFIX}control#{i}" do |control|
      control.vm.hostname = "#{LABEL_PREFIX}control#{i}"
      if ASSIGN_STATIC_IP
        control.vm.network :private_network,
          ip: "#{PUBLIC_SUBNET}.#{$last_ip_pub_digit+=1}"
      end
      # Virtualbox
      control.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', "#{MEMORY}"]
      end

      # VMware
      control.vm.provider :vmware_fusion do |v|
        v.vmx['memsize'] = "#{MEMORY}"
      end

      # Libvirt
      control.vm.provider :libvirt do |lv|
        lv.memory = MEMORY
        lv.random_hostname = true
        lv.storage :file, :size => '120G'
      end

      # Parallels
      control.vm.provider "parallels" do |prl|
        prl.name = "seed#{i}"
        prl.memory = "#{MEMORY}"
      end

      # Linode
      control.vm.provider :linode do |provider|
        provider.label = control.vm.hostname
      end
    end
  end

  (0..SEEDS - 1).each do |i|
    config.vm.define "#{LABEL_PREFIX}seed#{i}" do |seed|
      seed.vm.hostname = "#{LABEL_PREFIX}seed#{i}"
      if ASSIGN_STATIC_IP
        seed.vm.network :private_network,
          ip: "#{PUBLIC_SUBNET}.#{$last_ip_pub_digit+=1}"
      end
      # Virtualbox
      seed.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', "#{MEMORY}"]
      end

      # VMware
      seed.vm.provider :vmware_fusion do |v|
        v.vmx['memsize'] = "#{MEMORY}"
      end

      # Libvirt
      seed.vm.provider :libvirt do |lv|
        lv.memory = MEMORY
        lv.random_hostname = true
      end
      # Parallels
      seed.vm.provider "parallels" do |prl|
        prl.name = "seed#{i}"
        prl.memory = "#{MEMORY}"
      end

      seed.vm.provider :linode do |provider|
        provider.label = seed.vm.hostname
      end
    end
  end



  (0..BAREMETALS - 1).each do |i|
    config.vm.define "#{LABEL_PREFIX}baremetal#{i}" do |bm|
      bm.vm.hostname = "#{LABEL_PREFIX}baremetal#{i}"
      if ASSIGN_STATIC_IP
        bm.vm.network :private_network,
          ip: "#{PUBLIC_SUBNET}.#{$last_ip_pub_digit+=1}"
        bm.vm.network :private_network,
          ip: "#{CLUSTER_SUBNET}.#{$last_ip_cluster_digit+=1}"
      end
      # Virtualbox
      bm.vm.provider :virtualbox do |vb|
        # Create our own controller for consistency and to remove VM dependency
        unless File.exist?("disk-#{i}-0.vdi")
          # Adding OSD Controller;
          # once the first disk is there assuming we don't need to do this
          vb.customize ['storagectl', :id,
                        '--name', 'OSD Controller',
                        '--add', 'scsi']
        end

        (0..2).each do |d|
          vb.customize ['createhd',
                        '--filename', "disk-#{i}-#{d}",
                        '--size', '11000'] unless File.exist?("disk-#{i}-#{d}.vdi")
          vb.customize ['storageattach', :id,
                        '--storagectl', 'OSD Controller',
                        '--port', 3 + d,
                        '--device', 0,
                        '--type', 'hdd',
                        '--medium', "disk-#{i}-#{d}.vdi"]
        end
        vb.customize ['modifyvm', :id, '--memory', "#{MEMORY}"]
      end

      # VMware
      bm.vm.provider :vmware_fusion do |v|
        (0..1).each do |d|
          v.vmx["scsi0:#{d + 1}.present"] = 'TRUE'
          v.vmx["scsi0:#{d + 1}.fileName"] =
            create_vmdk("disk-#{i}-#{d}", '11000MB')
        end
        v.vmx['memsize'] = "#{MEMORY}"
      end

      # Libvirt
      driverletters = ('a'..'z').to_a
      bm.vm.provider :libvirt do |lv|
        # always make /dev/sd{a/b/c} so that CI can ensure that
        # virtualbox and libvirt will have the same devices to use for OSDs
        (0..2).each do |d|
          lv.storage :file, :device => "hd#{driverletters[d]}", :size => '50G', :bus => "ide"
        end
        lv.memory = MEMORY
        lv.random_hostname = true
      end

      # Parallels
      bm.vm.provider "parallels" do |prl|
        prl.name = "ceph-osd#{i}"
        prl.memory = "#{MEMORY}"
        (0..1).each do |d|
          prl.customize ["set", :id,
                         "--device-add",
                         "hdd",
                         "--iface",
                         "sata"]
        end
      end

      bm.vm.provider :linode do |provider|
        provider.label = bm.vm.hostname
      end

      # Run the provisioner after the last machine comes up
      #osd.vm.provision 'ansible', &ansible_provision if i == (NOSDS - 1)
    end
  end
end
