Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "public_network", bridge: "admin1", ip: "172.29.10.101"
  config.vm.network "public_network", bridge: "tenant1", ip: "172.29.20.101"
  config.vm.network "public_network", bridge: "storage1", ip: "172.29.30.101"
end

