Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "private_network", bridge: "admin", ip: "172.29.10.201"
  config.vm.network "private_network", bridge: "tenant", ip: "172.29.20.201"
  config.vm.network "private_network", bridge: "storage", ip: "172.29.30.201"
end
