BOX_IMAGE = "debian/buster64"
NODE_COUNT = 8

Vagrant.configure("2") do |config|

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", bridge: "admin", ip: "172.29.10.2#{i}"
      subconfig.vm.network "private_network", bridge: "tenant", ip: "172.29.20.2#{i}"
      subconfig.vm.network "private_network", bridge: "storage", ip: "172.29.30.2#{i}"
      subconfig.vm.provider "virtualbox" do |v|
          v.memory = 4096
          v.cpus = 4
      end
    end
  end
end

